refact: update content (#20)

diff --git a/GIT/skeletons/dev-generic/bin/dev-TASK b/GIT/skeletons/dev-generic/bin/dev-TASK
--- a/GIT/skeletons/dev-generic/bin/dev-TASK
+++ b/GIT/skeletons/dev-generic/bin/dev-TASK
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 #
-# X_TASK_DESCRIPTION_X
+# Dev / X_TASK_X / X_COMPONENT_X / X_TASK_DESCRIPTION_X
 #
-# * Template: 1.0.1
+# * Template: 1.3.0
 #
 
 #
@@ -10,18 +10,40 @@
 #
 
 # shellcheck source=bin/dev-set
-source ./bin/dev-set || exit 1
+source ./bin/dev-set || { echo 'dev-set:Error: unable to load dev environment' 2>&1 && exit 1; }
 # shellcheck source=lib/bl64/bashlib64-core.bash
-source "${DEV_CICD_BASHLIB64}/bashlib64-core.bash" || exit 1
+source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-core.bash" || exit 1
+
+#
+# Globals
+#
+
+# Dev / Enable debugging? Set to YES to enable
+export DEV_CICD_DEBUG="${DEV_CICD_DEBUG:-}"
+
+#
+# Functions
+#
+
+function dev_X_TASK_X() {
+  bl64_dbg_app_show_function
+  bl64_msg_show_task "X_TITLE_X"
+  # X_FUNCTION_PLACEHOLDER_X
+}
+
+function dev_X_TASK_X_initialize() {
+  bl64_dbg_app_show_function
+  # X_INITILIZE_PLACEHOLDER_X
+}
 
 #
 # Main
 #
 
 [[ -n "$DEV_CICD_DEBUG" ]] && bl64_dbg_all_enable
+dev_X_TASK_X_initialize || exit $?
 
 bl64_msg_all_enable_verbose
-bl64_msg_show_batch_start 'X_TASK_X'
-bl64_msg_show_task "X_TITLE_X"
-# X_CODE_PLACEHOLDER_2_X
-bl64_msg_show_batch_finish $? 'X_TASK_X'
+bl64_msg_show_batch_start 'dev-X_TASK_X-X_COMPONENT_X'
+dev_X_TASK_X
+bl64_msg_show_batch_finish $? 'dev-X_TASK_X-X_COMPONENT_X'
diff --git a/Installer64/skeletons/installer/install-package b/Installer64/skeletons/installer/install-package
--- a/Installer64/skeletons/installer/install-package
+++ b/Installer64/skeletons/installer/install-package
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# Template: 2.1.0
+# Template: 2.2.0
 #######################################
 # Installer64 / Package installer
 #
@@ -29,6 +29,13 @@
 
 # BashLib64 location
 export INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+# X_IMPORTS_PLACEHOLDER_X
+  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+
+#
+# Globals
+#
+
 # Enable debugging? Set to YES to enable
 export INST64_DEBUG="${INST64_DEBUG:-}"
 # Base path for local applications
@@ -39,16 +46,6 @@ export INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
 export INST64_OPT_ROOT="${INST64_OPT_ROOT:-/opt}"
 # Location for temporary files
 export INST64_TMP="${INST64_TMP:-/tmp}"
-
-# shellcheck source=lib/bl64/bashlib64.bash
-source "${INST64_BASHLIB64}/bashlib64.bash" ||
-  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
-
-# X_IMPORTS_PLACEHOLDER_X
-
-#
-# Globals
-#
 
 # X_GLOBALS_PLACEHOLDER_X
 export INST64_X_APP_NAME_CAPS_X_PACKAGES=''
