feat: update catalog (#6)

diff --git a/Installer64/skeletons/installer/install-package b/Installer64/skeletons/installer/install-package
--- a/Installer64/skeletons/installer/install-package
+++ b/Installer64/skeletons/installer/install-package
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
-# Template: 1.0.0
+# Template: 1.1.0
 #######################################
-# Container64 / Package installer
+# Installer64 / Package installer
 #
 # Author: SerDigital64 (https://github.com/serdigital64)
-# Repository: https://github.com/automation64/container64
+# Repository: https://github.com/automation64/installer64
 # Version: 1.0.0
 #
 #######################################
@@ -27,13 +27,17 @@
 # Imports
 #
 
-# Environment Definition. See docs/base-environment.md for details
-export CNT64_BASHLIB64="${CNT64_BASHLIB64:-/opt/bl64/bashlib64.bash}"
-export CNT64_DEBUG="${CNT64_DEBUG:-}"
-# X_CODE_PLACEHOLDER_1_X
+# Base Installer64 parameters
+export INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64/bashlib64.bash}"
+export INST64_DEBUG="${INST64_DEBUG:-}"
+export INST64_INSTALLER_ROOT="${INST64_INSTALLER_ROOT:-/opt/installer64}"
+export INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
+export INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
+export INST64_OPT_ROOT="${INST64_OPT_ROOT:-/opt}"
+export INST64_TMP="${INST64_TMP:-/tmp}"
 
-# shellcheck source=SCRIPTDIR/../../lib/bashlib64.bash
-source "$CNT64_BASHLIB64" || { echo "Error: unable to load bashlib64 (${CNT64_BASHLIB64})" && exit 1; }
+# shellcheck source=SCRIPTDIR/../lib/bashlib64.bash
+source "$INST64_BASHLIB64" || { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
 
 #
 # Globals
@@ -56,7 +60,7 @@ source "$CNT64_BASHLIB64" || { echo "Error: unable to load bashlib64 (${CNT64_BA
 #   0: package installed ok
 #   >0: unable to install package
 #######################################
-function cnt64_X_APP_NAME_X_install() {
+function inst64_X_APP_NAME_X_install() {
   bl64_dbg_app_show_function
   # X_CODE_PLACEHOLDER_3_X
 }
@@ -72,7 +76,7 @@ function cnt64_X_APP_NAME_X_install() {
 #   0: initialization ok
 #   >: failed to initialize
 #######################################
-function cnt64_X_APP_NAME_X_initialize() {
+function inst64_X_APP_NAME_X_initialize() {
   bl64_dbg_app_show_function
   # X_CODE_PLACEHOLDER_4_X
 }
@@ -81,16 +85,16 @@ function cnt64_X_APP_NAME_X_initialize() {
 # Main
 #
 
-declare cnt64_X_APP_NAME_X_installer_description='Install application: X_APP_FULL_NAME_X'
-declare -i cnt64_X_APP_NAME_X_status=0
+declare inst64_X_APP_NAME_X_installer_description='Install application: X_APP_FULL_NAME_X'
+declare -i inst64_X_APP_NAME_X_status=0
 
 bl64_msg_all_enable_verbose
-bl64_msg_show_batch_start "$cnt64_X_APP_NAME_X_installer_description"
+bl64_msg_show_batch_start "$inst64_X_APP_NAME_X_installer_description"
 
-[[ -n "$CNT64_DEBUG" ]] && bl64_dbg_lib_enable
-cnt64_X_APP_NAME_X_initialize &&
-  cnt64_X_APP_NAME_X_install
-cnt64_X_APP_NAME_X_status=$?
+[[ -n "$INST64_DEBUG" ]] && bl64_dbg_lib_enable
+inst64_X_APP_NAME_X_initialize &&
+  inst64_X_APP_NAME_X_install
+inst64_X_APP_NAME_X_status=$?
 
-bl64_msg_show_batch_finish "$cnt64_X_APP_NAME_X_status" "$cnt64_X_APP_NAME_X_installer_description"
-exit $cnt64_X_APP_NAME_X_status
+bl64_msg_show_batch_finish "$inst64_X_APP_NAME_X_status" "$inst64_X_APP_NAME_X_installer_description"
+exit $inst64_X_APP_NAME_X_status
